### ISSUE TITLE
Feature request:new tab styles

### ISSUE THREAD

**Issue by ozky** [psemiletov/tea-qt#1]
I noticed there is only google chrome look tabs style,would be more better to include alternative tabs styles in tea.

**Comment by psemiletov** [comment]
The tabs are styled via View - Themes menu.

**Comment by ozky** [comment]
I don't mean tab colors those right side tab changers used to change tab to other tab.

**Comment by ozky** [comment]
This what i mean that can't changed from menu.
I draw to that screenshot what i mean those chrome look like tab selectors.
![tea](https://cloud.githubusercontent.com/assets/1551665/13855865/1583a7c0-ec7b-11e5-854e-18e2a0b42e72.jpg)
