### ISSUE TITLE
word highlighting on doubleclick

### ISSUE THREAD

**Issue by Smirftsch** [psemiletov/tea-qt#12]
perhaps I missed it, but I couldn't find it- is there an option to enable word highlighting? Such as you double click a variable and it highlights all occasions of it?

And while on it- can custom highlight languages be enabled/added? I'd miss GLSL (and maybe UnrealScript).

**Comment by psemiletov** [comment]
The way to add custom language highlight is described at the TEA manual. In short, you need to put the highlighting module (based on some module from the TEA source) to  $HOME/.config/tea/hls.
About the word highlighting - good idea, but I need to think about :)

**Comment by Smirftsch** [comment]
when looking for occurrences of a variable is word highlighting incredibly helpful, would be great if you could consider adding it :)

**Comment by Smirftsch** [comment]
Sorry, is this request still alive? :)

**Comment by Smirftsch** [comment]
Thank you! 
I compiled latest Git, but it doesn't seem to have any effect whatsoever, neither find nor double clicking on a word does something. How is it supposed to work?

**Comment by psemiletov** [comment]
It is supposed to work in a way described at the program manual, where all functions are described. Just put some word to the FIF (famous input field) and use "Search - Mark all found".

**Comment by Smirftsch** [comment]
I'm terribly sorry to stress this, it plain doesn't work for me. I haven't had the time in the last months to really check on that, so I was using as is. Now I just pulled the latest git but "Mark all found" plain does nothing.
I am on Debian buster right now, if that matters.

Other than that, the method you describe is way more circuitous than just double clicking on a word, could I ask you again to consider implementing it? It's really the only thing I am missing using this great editor.

**Comment by psemiletov** [comment]
Fixed with the last commit :) Thank you for the report!
