### ISSUE TITLE
The program closes

### ISSUE THREAD

**Issue by oleguka** [psemiletov/tea-qt#13]
Сreate new file/wrire anything (example: 'qwerty')/function/add to dictionary - application closes
![tea](https://user-images.githubusercontent.com/29583338/27398694-04c956a4-56d4-11e7-855a-74ed28c0ccf4.jpg)

**Comment by psemiletov** [comment]
Спасибо! Хотя у меня не получилось воспроизвести эту ошибку у себя, попробую разобраться.

**Comment by oleguka** [comment]
Воспроизводится на 7 и 10

**Comment by psemiletov** [comment]
Вероятно я починил ошибку, но еще не проверял под Windows 7. В XP ошибка не проявлялась.
