### ISSUE TITLE
website down

### ISSUE THREAD

**Issue by ShalokShalom** [psemiletov/tea-qt#14]
![screenshot_20170722_112946](https://user-images.githubusercontent.com/6344099/28490026-1931a8b6-6ed1-11e7-8df4-680ef271d025.png)

**Comment by psemiletov** [comment]
Yes, because semiletov.org now is down due to the overheating. There is a working mirror: http://tea.ourproject.org/

**Comment by ShalokShalom** [comment]
Can you link?
