### ISSUE TITLE
Build and autoupload AppImage to releases (using Travis CI)

### ISSUE THREAD

**Issue by Symbian9** [psemiletov/tea-qt#15]
Related
* https://github.com/psemiletov/eko/issues/5

**Comment by Symbian9** [comment]
@psemiletov, may You provide AppImage for latest releases of Tea & Eko?

**Comment by psemiletov** [comment]
No, because TEA and EKO are small )

**Comment by Symbian9** [comment]
> because TEA and EKO are small

If so, why there is binary for Windows and no for Linux? Why not Windows users should compile it itself too, as Linux users?

**Comment by psemiletov** [comment]
Because Linux exists in the form of many distros.

**Comment by Symbian9** [comment]
> Because Linux exists in the form of many distros.

That is why AppImage is universal binary for many Linux distros.

**Comment by psemiletov** [comment]
As i said before, TEA is a small program. Feel free to make AppImage, if you want.
