### ISSUE TITLE
Host downloads at GitHub

### ISSUE THREAD

**Issue by cup** [psemiletov/tea-qt#25]
its a little confusing that download are in 2 places:

- http://semiletov.org/tea#downloads
- http://tea.ourproject.org#downloads

it might make more sense to just host the downloads at GitHub:

http://github.com/psemiletov/tea-qt/releases

**Comment by psemiletov** [comment]
No, it is the lair of Microsoft :) 
Github releases are just the mirror.

**Comment by ryandesign** [comment]
Well, would it harm anything if you uploaded your release files to the GitHub release, in addition to where you currently host them?
