### ISSUE TITLE
6.1.0 broken on BSD

### ISSUE THREAD

**Issue by daniloegea** [psemiletov/tea-qt#27]
Hello,

the version 6.1.0 is broken on BSD, I guess the problem due to the changes like this:

`#if defined(Q_OS_LINUX)` changed by `#if defined(Q_OS_LINUX) || defined(Q_WS_X11)`

The compiler is including the joystick code and the building is failing:

In file included from main.cpp:26:
In file included from ./rvln.h:53:
In file included from ./document.h:52:
./myjoystick.h:15:10: fatal error: 'linux/joystick.h' file not found
#include <linux/joystick.h>

Thanks!

**Comment by psemiletov** [comment]
Thank you for the report! I hope I've fixed it at current master branch, can you test it if you please?

**Comment by psemiletov** [comment]
It seems it is fixed (I've set up FreeBSD in VirtualBox)
