### ISSUE TITLE
Build failure with Qt4: fatal error: 'QMimeDatabase' file not found

### ISSUE THREAD

**Issue by ryandesign** [psemiletov/tea-qt#28]
It looks like you still want to support Qt4, but I get this problem when trying to build tea 47.0.0 with Qt4:

```
In file included from todo.cpp:1:
./utils.h:16:10: fatal error: 'QMimeDatabase' file not found
#include <QMimeDatabase>
         ^~~~~~~~~~~~~~~
```

It looks like [QMimeDatabase is only in Qt5](http://doc.qt.io/qt-5/qmimedatabase.html).

**Comment by yurytch** [comment]
Needs patching with this:

[tea-qt-47.0.0_build.diff.gz](https://github.com/psemiletov/tea-qt/files/2633259/tea-qt-47.0.0_build.diff.gz)
