### ISSUE TITLE
building from source on osx - images & palettes missing

### ISSUE THREAD

**Issue by laymonk** [psemiletov/tea-qt#3]
Hello,

Thanks for putting out the sources for your great editor, Tea-QT, out here on github.  I use linux and osx in equal measures, and I am trying to build tea editor for osx from sources.

qmake complains about missing images and palettes folder, so I have commented out those references in the qrc file.  

Questions:
- I am wondering the impact of building without those resources
- If the images and palettes resources are significant, how can I obtain them? (src downloads from your websites is not working right now)
- I would like to follow through and attempt creating a [homebrew cask](https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md) of tea editor, and would appreciate any comments or suggestions towards doing this successfully and to your satisfaction.

Thanks ..

**Comment by laymonk** [comment]
Forgot to add the error messages from qmake:

> RCC: Error in 'rlvn.qrc': Cannot find file 'images/happy-people-bw.png'
RCC: Error in 'rlvn.qrc': Cannot find file 'images/mister.png'
RCC: Error in 'rlvn.qrc': Cannot find file 'images/moon-phases.png'
RCC: Error in 'rlvn.qrc': Cannot find file 'palettes/paper-old'
RCC: Error in 'rlvn.qrc': Cannot find file 'palettes/paper-toilet'
RCC: Error in 'rlvn.qrc': Cannot find file 'palettes/TEA'
RCC: Error in 'rlvn.qrc': Cannot find file 'palettes/UNIX'
RCC: Error in 'rlvn.qrc': Cannot find file 'palettes/Linux MC'
RCC: Error in 'rlvn.qrc': Cannot find file 'palettes/Pines'
RCC: Error in 'rlvn.qrc': Cannot find file 'palettes/Vinyl'
RCC: Error in 'rlvn.qrc': Cannot find file 'palettes/Berry'
RCC: Error in 'rlvn.qrc': Cannot find file 'palettes/Turbo90'

**Comment by psemiletov** [comment]
Oops! I forgot to put palettes and images directories into the git. Fixed!

**Comment by psemiletov** [comment]
It the compilation on Mac works now?

**Comment by laymonk** [comment]
Thanks for the quick response.  Yes, this makes qmake and make happier, and I was able to build and install tea.  I am currently running it now.

So, any thoughts on trying to get a homebrew cask made for tea-qt?

**Comment by psemiletov** [comment]
It is a fine idea to create the cask! :)
By the way I didn't know about Howebrew and casks before, because I'm far away from the Mac world.

**Comment by tjuerges** [comment]
No need to buy a Mac.  There also is [Linuxbrew](https://github.com/Linuxbrew/).  :-)
