### ISSUE TITLE
При сборке с %qmake_qt5 много предупреждений -Wunused-parameter

### ISSUE THREAD

**Issue by Alzimzim** [psemiletov/tea-qt#31]
`+ /usr/bin/qmake-qt5 libsuff=64 'QMAKE_CFLAGS=-O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -DPIC -fPIC' 'QMAKE_CXXFLAGS=-O2 -Wa,--compress-debug-sections -gdwarf-4 -fvar-tracking-assignments -frecord-gcc-switches -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -ffat-lto-objects -fno-delete-null-pointer-checks -fstack-protector --param=ssp-buffer-size=4 -fPIC -DPIC -fPIC' QMAKE_CXXFLAGS_RELEASE= 'QMAKE_LFLAGS= -Wl,--as-needed -Wl,--no-undefined -Wl,-z,now -Wl,-z,relro -Wl,-O1 -Wl,--build-id -Wl,--enable-new-dtags -Wl,--hash-style=gnu'
Info: creating stash file /home/alzim/rpmbuild/BUILD/tea-qt-50.0.1/.qmake.stash
Project MESSAGE: +JOYSTICK_SUPPORTED
Project MESSAGE: Zlib found
Project MESSAGE: ASpell enabled
Project MESSAGE: hunspell enabled
Empty filename passed to function
Empty filename passed to function
+ /usr/bin/make -j4 -s
In file included from rvln.h:58:0,
                 from main.cpp:26:
spellchecker.h:46:33: предупреждение: параметр «lang» не используется [-Wunused-parameter]
   CSpellchecker (const QString &lang,
                                 ^
spellchecker.h:47:33: предупреждение: параметр «path» не используется [-Wunused-parameter]
                  const QString &path,
                                 ^
spellchecker.h:48:33: предупреждение: параметр «user» не используется [-Wunused-parameter]
                  const QString &user): initialized {false} {};
                                 ^
In file included from rvln.h:58:0,
                 from rvln.cpp:74:
spellchecker.h:46:33: предупреждение: параметр «lang» не используется [-Wunused-parameter]
   CSpellchecker (const QString &lang,
                                 ^
spellchecker.h:47:33: предупреждение: параметр «path» не используется [-Wunused-parameter]
                  const QString &path,
                                 ^
spellchecker.h:48:33: предупреждение: параметр «user» не используется [-Wunused-parameter]
                  const QString &user): initialized {false} {};
                                 ^
rvln.cpp:2345:93: предупреждение: параметр «previous» не используется [-Wunused-parameter]
 void rvln::slot_lv_menuitems_currentItemChanged (QListWidgetItem *current, QListWidgetItem *previous)
                                                                                             ^
rvln.cpp:4906:36: предупреждение: параметр «exitCode» не используется [-Wunused-parameter]
 void rvln::cb_script_finished (int exitCode, QProcess::ExitStatus exitStatus)
                                    ^
rvln.cpp:4906:67: предупреждение: параметр «exitStatus» не используется [-Wunused-parameter]
 void rvln::cb_script_finished (int exitCode, QProcess::ExitStatus exitStatus)
                                                                   ^
rvln.cpp:7917:45: предупреждение: параметр «year» не используется [-Wunused-parameter]
 void rvln::calendar_currentPageChanged (int year, int month)
                                             ^
rvln.cpp:7917:55: предупреждение: параметр «month» не используется [-Wunused-parameter]
 void rvln::calendar_currentPageChanged (int year, int month)
                                                       ^
document.cpp:525:95: предупреждение: параметр «fname» не используется [-Wunused-parameter]
 CSyntaxHighlighter::CSyntaxHighlighter (QTextDocument *parent, CDocument *doc, const QString &fname): QSyntaxHighlighter (parent), document {doc}
                                                                                               ^
document.cpp:1728:47: предупреждение: параметр «newBlockCount» не используется [-Wunused-parameter]
 void CTEAEdit::updateLineNumberAreaWidth (int newBlockCount)
                                               ^
document.cpp:2065:56: предупреждение: параметр «source» не используется [-Wunused-parameter]
 bool CTEAEdit::canInsertFromMimeData (const QMimeData *source)
                                                        ^
In file included from spellchecker.cpp:34:0:
spellchecker.h:46:33: предупреждение: параметр «lang» не используется [-Wunused-parameter]
   CSpellchecker (const QString &lang,
                                 ^
spellchecker.h:47:33: предупреждение: параметр «path» не используется [-Wunused-parameter]
                  const QString &path,
                                 ^
spellchecker.h:48:33: предупреждение: параметр «user» не используется [-Wunused-parameter]
                  const QString &user): initialized {false} {};
                                 ^
spellchecker.cpp:113:60: предупреждение: параметр «word» не используется [-Wunused-parameter]
 void CAspellchecker::remove_from_user_dict (const QString &word)
                                                            ^
fman.cpp:260:84: предупреждение: параметр «previous» не используется [-Wunused-parameter]
 void CFMan::cb_fman_currentChanged (const QModelIndex &current, const QModelIndex &previous )
                                                                                    ^
img_viewer.cpp:354:43: предупреждение: параметр «event» не используется [-Wunused-parameter]
 void CZORWindow::paintEvent (QPaintEvent *event)
                                           ^
fontbox.cpp:38:54: предупреждение: параметр «text» не используется [-Wunused-parameter]
 void CFontBox::slot_fontname_changed (const QString &text)
                                                      ^
fontbox.cpp:44:44: предупреждение: параметр «i» не используется [-Wunused-parameter]
 void CFontBox::slot_font_size_changed (int i)
                                            ^
tio.cpp:268:41: предупреждение: параметр «fname» не используется [-Wunused-parameter]
 bool CTioReadOnly::save (const QString &fname)
                                         ^
zip.c: В функции «zipOpenNewFileInZip4_64»:
zip.c:1086:70: предупреждение: параметр «crcForCrypting» не используется [-Wunused-parameter]
                                          const char* password, uLong crcForCrypting,
                                                                      ^
In file included from rvln.h:58:0,
                 from moc_rvln.cpp:9:
spellchecker.h:46:33: предупреждение: параметр «lang» не используется [-Wunused-parameter]
   CSpellchecker (const QString &lang,
                                 ^
spellchecker.h:47:33: предупреждение: параметр «path» не используется [-Wunused-parameter]
                  const QString &path,
                                 ^
spellchecker.h:48:33: предупреждение: параметр «user» не используется [-Wunused-parameter]
                  const QString &user): initialized {false} {};
                                 ^
+ exit 0
`

**Comment by psemiletov** [comment]
Спасибо! Это нормально.
