### ISSUE TITLE
semiletov.org timing out for me in the UK

### ISSUE THREAD

**Issue by grahamperrin** [psemiletov/tea-qt#38]
Hi

https://github.com/psemiletov/tea-qt/blob/ca2fef370a75c9b71ffcdb36f26f34b4a994b30c/README#L4 

Firefox reports: 

> … The server at semiletov.org is taking too long to respond. …

Similarly in surf: 

> Could not connect: Operation timed out

https://downforeveryoneorjustme.com/semiletov.org

> It's just you. semiletov.org is up.

**Comment by grahamperrin** [comment]
Please ignore this. Sorry. 

In the same room, with a different computer and a wired connection, I _can_ get the page in `lynx`. 

For my main computer: maybe an issue with my choice of DNS at the wireless router in this room.

**Comment by psemiletov** [comment]
Sometime smiletov.org is down, because it is hosted in my room :)

**Comment by grahamperrin** [comment]
:-)
