### ISSUE TITLE
TEA 60: Wrong Qt version check in `#if QT_VERSION < 0x050500`

### ISSUE THREAD

**Issue by schragge** [psemiletov/tea-qt#40]
According to [Qt docs](https://doc.qt.io/qt-5/qt.html#MatchFlag-enum), `Qt::MatchRegularExpression` was added in Qt 5.15, not Qt 5.5.
`#if QT_VERSION < 0x050500` [here](https://github.com/psemiletov/tea-qt/blob/9e6615e2dafe297b3a7d5ec2fd7cde78b305389d/tea.cpp#L36) and everywhere else in the file `tea.cpp` should be changed to `#if QT_VERSION < 0x050F00` or, even better, to
```
#if QT_VERSION < QT_VERSION_CHECK(5, 15, 0)
```
Otherwise, TEA 60 fails to build from source on CentOS 8 which includes Qt 5.12.
For now, I just `sed -i '/QT_VERSION/s/0x050500/0x050F00/' tea.cpp`

**Comment by psemiletov** [comment]
It's not better bacause TEA needs 0x050500 to check availability of QRegularExpression search at QTextDocument, so the global "sed" is a good solution for the CentOS only.

**Comment by schragge** [comment]
But this is exactly what I'm speaking about. `QRegularExpression` isn't available in Qt 5.12.5.

**Comment by schragge** [comment]
Nope. TEA checks for `QRegularExpression` presence with
```
#if QT_VERSION >= 0x050000
```
This check isn't affected by the proposed change.

**Comment by schragge** [comment]
The last commits in master fix this. Thank you.
