### ISSUE TITLE
TEA 60: Unsufficient language declaration when setting global compiling arguments in `meson.build`

### ISSUE THREAD

**Issue by schragge** [psemiletov/tea-qt#41]
TEA 60  fails to build from source on CentOS 8 because the following lines in `meson.build`
```
add_global_arguments('-DNOCRYPT="1"', language : 'cpp')
add_global_arguments('-DNOUNCRYPT="1"', language : 'cpp')
```
are only defined for `cpp`, but not for `c` (the compile error being detected in `zip.c`).
For now, I just `sed -i "/CRYPT/s/'cpp'/[&,'c']/" meson.build`

I guess it may be related to `crypt.h` having been patched out from `zlib-devel` in Fedora 28 as per [#rhbz1424609](https://bugzilla.redhat.com/show_bug.cgi?id=1424609). RHEL 8 is based on Fedora 28 and includes this patch.

**Comment by psemiletov** [comment]
Can you try please the current master commit? I think there is all CentOS related issues are fixed. I cannot test it for myselft because CentOS that I set up in VirtualBox don't want to download any packages from the mirror by default, and It can be too long for me to deal with it properly :)

**Comment by schragge** [comment]
I confirm the fixes work. Thank you.

**Comment by psemiletov** [comment]
Thank you!
