### ISSUE TITLE
error: use of undeclared identifier 'multiLineCommentFormat'

### ISSUE THREAD

**Issue by ryandesign** [psemiletov/tea-qt#42]
Hi! I maintain [tea-qt in MacPorts](https://ports.macports.org/port/tea) and in trying to update it to version 60.0.2 I encountered these errors:

```
document.cpp:227:22: error: use of undeclared identifier 'multiLineCommentFormat'
                     multiLineCommentFormat = fmt;
                     ^
document.cpp:324:48: error: use of undeclared identifier 'multiLineCommentFormat'
         setFormat (startIndex, commentLength, multiLineCommentFormat);
                                               ^
```

I am building on macOS 10.13.6 with qmake from Qt 4.8.7, which I realize is old, and I will try to switch to Qt 5 and building with CMake.

**Comment by psemiletov** [comment]
Please try the new, fixed release - https://github.com/psemiletov/tea-qt/archive/refs/tags/60.0.3.tar.gz

**Comment by ryandesign** [comment]
Thanks for the quick fix. 60.0.3 does compile for me with Qt 4.

**Comment by psemiletov** [comment]
Thank you!
