### ISSUE TITLE
Conflict with a different tea package in arch repo

### ISSUE THREAD

**Issue by FabioLolix** [psemiletov/tea-qt#50]
Hello Peter

A different 'tea' package have been added to Arch official repo https://archlinux.org/packages/community/x86_64/tea/

and now the packages are in conflict, so seems it is time to rename/rebranding to tea-qt

**Comment by psemiletov** [comment]
Not at the TEA source level. TEA is far older and mature than "Gitea" command line tool.

**Comment by psemiletov** [comment]
I've fixed it at tea-qt-git package with rename of tea executable and at tea.desktop file entry.

**Comment by FabioLolix** [comment]
> Not at the TEA source level. TEA is far older and mature than "Gitea" command line tool.

Yeah, I know but it has gone this way

For the pkgbuild pkgrel need to bumped to 2 (pkgrel=2)

and provide/conflicts adjusted

provides=('tea-qt')
conflicts=('tea-qt')

**Comment by psemiletov** [comment]
Thank you!
