### ISSUE TITLE
Add support to build with CopperSpice?

### ISSUE THREAD

**Issue by 3oheicrw** [psemiletov/tea-qt#57]
After an hour hacking with cmake I could have this project able to build with CopperSpice but the compilation failed because of the incompatibility between CopperSpice and Qt. Most notably I have to hard code the Qt version (CopperSpice should be on par with Qt5) and CopperSpice has changed QString to UTF-8 instead of UTF-16 like on Qt that caused many type mismatch problems. As you already support Qt from version 4 up to version 6. Could you add support to build with CopperSpice too? There must be changes in code to do so.

https://github.com/copperspice

**Comment by psemiletov** [comment]
It is too much work to support CopperSpice in TEA.
