### ISSUE TITLE
Never ending windows with; Please set up spell checker dictionaries at  Options - Functions page

### ISSUE THREAD

**Issue by clach04** [psemiletov/tea-qt#65]
1. Installed https://github.com/psemiletov/tea-qt/releases/tag/62.0.0 (latets stable, binary) for first time on Windows 10 machine.
2. opened English text file
3. chose spell check from menu

Window pops up with:

>!
>  Please set up spell checker dictionaries at  Options - Functions page

![image](https://github.com/psemiletov/tea-qt/assets/424032/208882a3-1962-4aa3-b77a-ff04609f2ac6)

Hit OK to close... and it comes back again, and again, and again, program unresponsive.
Close all windows does not work. Have to `taskkill /PID ...`

**Comment by psemiletov** [comment]
Thank you, fixed today at [](https://github.com/psemiletov/tea-qt/releases/download/62.1.2/tea-62.1.2-qt5-install.exe)

**Comment by clach04** [comment]
Fixed by https://github.com/psemiletov/tea-qt/commit/3288106115bc9afb57e40965379c92daee3510b0
