### ISSUE TITLE
Unknown CMake command "qt_standard_project_setup"

### ISSUE THREAD

**Issue by ryandesign** [psemiletov/tea-qt#66]
I tried building TEA 62.1.2 on macOS 12.7.1 with CMake 3.28.0-rc5 and Qt 5.15.11 installed using MacPorts. It failed, saying:

```
CMake Error at CMakeLists.txt:28 (qt_standard_project_setup):
  Unknown CMake command "qt_standard_project_setup".
```

Looks like the unconditional use of `qt_standard_project_setup` was added to CMakeLists.txt in 5b1ba4fc34d8bc830a236e29a11a2158a7010088 but `qt_standard_project_setup` [was introduced in Qt 6.3](https://doc.qt.io/qt-6/qt-standard-project-setup.html) so that won't work for Qt 5.

**Comment by psemiletov** [comment]
Thank you, actually it affected all platforms. Fixed at 62.2.0.
