### ISSUE TITLE
Opening in gnome (nautilus)

### ISSUE THREAD

**Issue by Smirftsch** [psemiletov/tea-qt#7]
Hey there, great editor, was looking for something like this all the time in Linux!
I have some minor, but annoying problem, using gnome (nautilus) Tea refuses to open new documents when already open. I need to close it in order to load the document (.txt file). I set it as default editor in gnome. Also would be nice to have it showing up if I click a file which is already open in a tab (perhaps the same issue?). This might be some problem with gnome or tea, or both, or plain some setting I haven't found so far. 
I haven't tried yet in another window manager.
Keep up the good work!

**Comment by psemiletov** [comment]
I'll try to install Gnome and test TEA in Nautilus. With KDE file opening works fine. Thank you for the report!

**Comment by Smirftsch** [comment]
I had an idea and tried from console:
"QLocalSocket::connectToServer: Connection refused"

is what I get when already open.

**Comment by Smirftsch** [comment]
had some time yesterday and compiled latest git. Problem persists.

**Comment by psemiletov** [comment]
Thanks, I need some more time :)

**Comment by psemiletov** [comment]
Can you show me the contents of tea.desktop file from your system? It must be at /usr/share/applications. Nautilus uses the "exec" line from there to run TEA.

**Comment by Smirftsch** [comment]
[Desktop Entry]
Version=1.0
Name=TEA
Exec=tea %U
Icon=tea
Terminal=false
Type=Application
GenericName=TEA Text Editor
Comment=Powerful text editor on Qt
Comment[ru]=Функциональный текстовый редактор на Qt
Categories=Utility;TextEditor;
MimeType=text/english;text/plain;text/x-makefile;text/x-c++hdr;text/x-c++src;text/x-chdr;text/x-csrc;text/x-java;text/x-moc;text/x-pascal;text/x-tcl;text/x-tex;application/x-shellscript;text/x-c;text/x-c++;

here we go :)

**Comment by psemiletov** [comment]
What if we change "tea %U" to "tea %f"?

**Comment by Smirftsch** [comment]
no changes, unfortunately.

**Comment by psemiletov** [comment]
So, I've tried some DE other than KDE. It seems that QLocalSocket that TEA uses for the single-application mechanism works fine at KDE only :) The logical next step for me is to rewrite single-application  code and test is with different DE's. Thank's for your help! I never think that such important bug was hidden in TEA.

**Comment by Smirftsch** [comment]
Happy I could help a bit!

**Comment by psemiletov** [comment]
I think I have fixed it. Can you try current version from github? Now TEA, on UNIXes uses the shared memory instead of sockets, and on my Gnome now all works good as in KDE.

**Comment by Smirftsch** [comment]
Sorry for delay, wasn't at home a few days.
Works, just one thing left perhaps, it doesn't maximize the tea window again when opening the new file, it stays minimized. No idea if this is intentional, I think such behavior can be wanted sometimes too, but if so an option to configure this behavior would be nice.
Thanks!!

**Comment by psemiletov** [comment]
Do you mean the window maxizing or just the visibility? Currently I've add some fixes that forces to show TEA window after open the file. Is now that is the behavior you talk about?

**Comment by Smirftsch** [comment]
yes, that's exactly it:)

**Comment by psemiletov** [comment]
Thank you for your help!
